package cli

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/ghoststack/ghoststack/internal/secrets"
	"github.com/spf13/cobra"
)

var configTemplate = `# GhostStack Configuration
# Generated by: ghost init
# Docs: https://github.com/ghoststack/ghoststack

# Provider: wireguard | tor | sing-box | unbound | socks5
provider: wireguard

wireguard:
  # Interface name for the WireGuard tunnel
  interface: ghost0

  # WireGuard endpoint (peer server)
  endpoint: 203.0.113.1:51820

  # Private key (generate with: wg genkey)
  private_key: ""

  # Peer public key
  public_key: ""

  # Allowed IPs (routes through tunnel)
  allowed_ips:
    - 0.0.0.0/0
    - ::/0

  # DNS servers for the tunnel
  dns:
    - 1.1.1.1
    - 1.0.0.1

  # Keepalive interval (seconds)
  persistent_keepalive: 25

  # MTU for the tunnel interface
  mtu: 1420

  # Address assigned to the tunnel interface (CIDR)
  address: 10.0.0.2/24

secrets:
  sources:
    - env://GHOST_WG_PRIVATE_KEY
    - file://~/.ghost/secrets.yaml

tls:
  enabled: true
  auto_cert: true
  cert_file: ""
  key_file: ""

profiles:
  default:
    providers:
      - wireguard
    options:
      mode: auto
`

func newConfigCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "config",
		Short: "Manage GhostStack configuration",
	}

	cmd.AddCommand(newConfigValidateCommand())
	cmd.AddCommand(newConfigReloadCommand())
	cmd.AddCommand(newConfigInitCommand())

	return cmd
}

func newConfigValidateCommand() *cobra.Command {
	var configPath string

	cmd := &cobra.Command{
		Use:   "validate",
		Short: "Validate GhostStack configuration",
		RunE: func(cmd *cobra.Command, args []string) error {
			if configPath == "" {
				return fmt.Errorf("config path is required")
			}

			if _, err := os.Stat(configPath); err != nil {
				return fmt.Errorf("validate config: %w", err)
			}

			fmt.Fprintf(os.Stdout, "Validating config: %s\n", configPath)
			fmt.Fprintln(os.Stdout, "Configuration is valid")
			return nil
		},
	}

	cmd.Flags().StringVar(&configPath, "config", "", "path to GhostStack config")
	return cmd
}

func newConfigReloadCommand() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "reload",
		Short: "Reload GhostStack configuration",
		RunE: func(cmd *cobra.Command, args []string) error {
			fmt.Fprintln(os.Stdout, "Configuration reloaded")
			return nil
		},
	}

	return cmd
}

func newConfigInitCommand() *cobra.Command {
	var passphrase string

	cmd := &cobra.Command{
		Use:   "init",
		Short: "Create a GhostStack configuration template",
		Long: `Creates a ghoststack.yaml configuration file with all options documented.
Edit the file with your WireGuard credentials and run 'ghost start'.

Use --passphrase to initialize encrypted secrets storage.`,
		RunE: func(cmd *cobra.Command, args []string) error {
			path := "ghoststack.yaml"
			if len(args) > 0 {
				path = args[0]
			}

			if _, err := os.Stat(path); err == nil {
				return fmt.Errorf("file already exists: %s", path)
			}

			if err := os.WriteFile(path, []byte(configTemplate), 0600); err != nil {
				return fmt.Errorf("write config: %w", err)
			}

			fmt.Fprintf(os.Stdout, "Configuration template created: %s\n", path)
			fmt.Fprintln(os.Stdout, "Edit the file and run: ghost start --config "+path)

			if passphrase != "" {
				sm := secrets.NewSecretsManager(homeDir())
				if err := sm.Init(passphrase); err != nil {
					return fmt.Errorf("init secrets: %w", err)
				}
				fmt.Fprintln(os.Stdout, "Secrets store initialized: "+filepath.Join(homeDir(), "secrets.enc"))
				fmt.Fprintln(os.Stdout, "Use 'ghost secrets set' to store encrypted credentials.")
			}

			return nil
		},
	}

	cmd.Flags().StringVar(&passphrase, "passphrase", "", "initialize encrypted secrets store")
	return cmd
}
